pinellolab/DNA-Diffusion

Contributors.md
README.md

Resolve issue of what is a contribution.
Added contributor list to an independant file. I added any person that made a pull request or push. That is my initial idea of contributors, but this can keep being updated before the merge until we discuss "what is a contribution" on wedsnday. 
And I dont know the full name of @jxilt

Resolve contributor list in an independant file

---

.github/workflows/ci.yml
pyproject.toml
requirements.txt

Tackles #20 
* Test across 3 python versions and all systems (`3.8` being the minimum because the latest version of `numpy` doesn't support `3.7`)
---
However this requires a `requirements.txt` file to function as intended.

feat: Add Github Actions for Testing

---

.github/workflows/ci.yml
requirements.txt
tests/data/test_sequence_dataloader.py

Based on discussion with @mateibejan1, running the tests on the `codebase` branch is also essential. It's the branch which is under heavy development and we should ensure all tests pass before we merge into `codebase` as well.

feat(ci): Add `codebase` branch to CI

---

.github/PULL_REQUEST_TEMPLATE.md

misc: create a PR template

---

dna-diffusion/metrics/gene_expression/enformer/eval.py

Addding an evaluation script for enformer
Reviewers: @aaronwtr

Enformer implementation dev ethan

---

.github/workflows/ci.yml

Add the `cache-dependency-path` argument

feat(ci): add `cache-dependency-path`

---

src/data/sequence_dataloader.py

Updated and added existing data classes in line with our latest experiments
1. Dataloading() class currently only splits the data into training/validation/testing. At a later point I will add the functions that let us recreate our current subset dataset from the master file. This current format should keep things simple for running on cluster.
2. DataPreprocessing() class is a modified version of an existing class from our notebook that is used to extract motif information for later results. 
3. Few changes to SequenceDatasetBase class. Main change involves formatting differences for certain arguments that it receives. 
4. SequenceDataModule has been simplified and dataset splitting is called within this class now. 
5. Tests also may not work anymore with format change

Codebase:  Dataloader update - cell type conditioning replacing component conditioning.

---

CODE_OF_CONDUCT.md

* see https://www.contributor-covenant.org/
* resolves #77

add contributor covenant code of conduct

---

.github/workflows/inactive-issues-prs.yml

* mark issues stale 60/close 7
* consider PRs stale 60/close 14
* resolves #81

add actions/stale for issues and prs

---

dnadiffusion/metrics/sampling_metrics.py

* Resolves #107 
* After rebasing in last PR, validation metrics appear in both sampling_metrics.py and validation_metrics.py. 
* Removes duplicate copy of metrics and better organizes codebase

Removed validation metrics from sampling metrics

---

.github/workflows/docker.yml
dockerfiles/Dockerfile

add docker container

---

.github/release-drafter.yml
.github/workflows/release.yml
.github/workflows/test-release.yml
dockerfiles/Dockerfile

add release workflows

---

.github/workflows/docker.yml
.github/workflows/release.yml
.github/workflows/test-release.yml
dockerfiles/Dockerfile
src/dnadiffusion/configs.py
src/dnadiffusion/data/dataloader.py

make release depend on build and docker

---

pyproject.toml

pin package versions

---

pyproject.toml

pin memory-efficient-attention-pytorch to final release version

---

.github/mergify.yml
.github/workflows/docker.yml
dockerfiles/Dockerfile
environments/conda/environment.yml

update to torch `2.1.0`

---

src/dnadiffusion/models/unet.py
train.py

* Resolves #235 
* removes the need for find_unused_parameters=True from accelerator

fix cross_attention, removed unused_parameters flag

---

README.md

add contributor graph

---

src/dnadiffusion/models/unet.py

fix bug caused by taking length of itertools.pairwise()

---

pyproject.toml

ignore ruff rule related to pairwise preference over zip

---

.github/workflows/build.yml
pyproject.toml

Bump codecov to v4

---

.gitattributes

fix: add linguist config

---

uv.lock

fix(uv.lock): update uv to 0.7.2 & update lock file

---

pyproject.toml
uv.lock

fix(docs): update pyproject.toml to allow for python handlers in docs

---

.github/workflows/release.yml
.github/workflows/test-release.yml
pyproject.toml

feat(release): allow uv to manage build, release, and publish

---

.github/workflows/release.yml
.github/workflows/test-release.yml

chore(release): provide tokens for testpypi and pypi
